### ISSUE TITLE
has this been fixed?

### ISSUE THREAD

**Issue by jonschlinkert** [akileez/Assemble6.1#1]
@akileez just wanted to check in and see if this is all working for you now. If not, we'll get it fixed

**Comment by akileez** [comment]
to be honest, I haven't even looked at this yet. Give me a few mins. I've been busy refactoring helpers and my new assemblefile.

**Comment by akileez** [comment]
@jonschlinkert works lik a charm! thanks a million.

**Comment by jonschlinkert** [comment]
:+1:
